export const IMPORTS = {
  cpp: '#include <iostream>\n#include <fstream>\n#include <sstream>\n#include <vector>\n#include <string>\n#include <list>\n#include <deque>\n#include <set>\n#include <unordered_set>\n#include <map>\n#include <unordered_map>\n#include <stack>\n#include <queue>\n#include <array>\n#include <tuple>\n#include <algorithm>\n#include <utility>\n#include <functional>\n#include <numeric>\n#include <iterator>\n#include <bitset> \n#include <random>\n#include <cmath>\n#include <ctime> \n#include <chrono>\n#include <limits>\n#include <memory>\n#include <cassert>\n\n\nusing namespace std;',
  csharp:
    'using System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing System.Text;\nusing System.Threading.Tasks;\nusing System.Collections;\nusing System.IO;\nusing System.Text.RegularExpressions;\nusing System.Diagnostics;\nusing System.Numerics;\nusing System.Threading;\nusing System.Collections.Concurrent;',
  java: 'import java.util.*;\nimport java.util.stream.*;\nimport java.util.function.*;\nimport java.util.concurrent.*;\nimport java.util.regex.*;\nimport java.util.Map.Entry;\nimport java.util.PriorityQueue;\nimport java.util.LinkedList;\nimport java.util.ArrayList;\nimport java.util.Stack;\nimport java.util.Queue;\nimport java.util.Deque;\nimport java.util.HashMap;\nimport java.util.HashSet;\nimport java.util.TreeMap;\nimport java.util.TreeSet;\nimport java.io.*;\nimport java.math.*;\nimport java.lang.Exception;',
  python:
    'import collections\nfrom collections import Counter, defaultdict, deque, OrderedDict\nimport heapq\nimport itertools\nimport math\nimport random\nimport re\nimport string\nimport sys\nimport bisect\nimport functools\nfrom functools import lru_cache, reduce\nimport operator\nimport time\nimport array\nfrom queue import PriorityQueue, Queue, LifoQueue\nimport copy\nimport pprint\nfrom typing import List, Dict, Set, Tuple, Optional, Union, Any\nimport struct\nfrom datetime import datetime, timedelta\nimport os\nimport json\nimport csv\nimport statistics\nimport decimal\nfrom decimal import Decimal\nfrom typing import *\nimport unittest\nimport heapq\nfrom heapq import *\n\n\nclass ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n',
  javascript: '',
};
