const PRISMA_ERROR_CODES = {
  INVALID_INPUT: 'P2000',
  UNIQUE_CONSTRAINT_FAILED: 'P2002',
  FOREIGN_KEY_CONSTRAINT_FAILED: 'P2003',
  RECORD_NOT_FOUND: 'P2025',
};

export default PRISMA_ERROR_CODES;
